(()=>{
  const q=s=>document.querySelector(s), esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const key='agentos-mcp-scopes'; let runs=[]; let lastRun=null; const compared=new Set();
  const getScopes=()=>{try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}};
  const saveScopes=s=>localStorage.setItem(key,JSON.stringify(s));
  const inject=()=>{if(document.querySelector('link[data-feature-css]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='/feature-pack.css?v=20260911';l.dataset.featureCss='1';document.head.appendChild(l);const theme=document.createElement('link');theme.rel='stylesheet';theme.href='/unified-theme.css?v=20260920';theme.dataset.unifiedTheme='1';document.head.appendChild(theme);document.body.classList.remove('theme-paper','theme-mint');document.body.classList.add('theme-ink');localStorage.setItem('agentos-theme','ink');const st=document.createElement('style');st.textContent='.approval-demo{margin-top:10px;border:1px solid #e98b70;border-radius:8px;background:#2a2425;color:#f3b094;padding:8px 10px;font:700 10px DM Mono;cursor:pointer}.approval-request{display:grid;gap:7px;margin-top:15px;padding:14px;border:1px solid #815447;border-radius:10px;background:#241d20}.approval-request b{color:#f2b094;font-size:11px}.approval-request span{color:#edf2f2;font:12px/1.45 Manrope}.approval-request small{color:#a98c8f;font:9px DM Mono}.theme-picker{display:none!important}.console-foot{gap:12px!important;padding:8px 12px!important;align-items:center!important}.console-foot .mission-link{flex:0 0 auto!important;margin:0 8px 0 0!important;white-space:nowrap!important;line-height:1.2!important}.console-foot .mode{gap:8px!important;flex:1 1 auto!important}.console-foot .mode label{white-space:nowrap!important}.console-foot .mode select{height:38px!important;padding:0 30px 0 12px!important;font-size:12px!important;border-radius:9px!important}.console-foot .cook-btn{flex:0 0 auto!important;min-width:168px!important;height:46px!important;padding:0 18px!important;border-radius:10px!important;font-size:13px!important;display:inline-flex!important;align-items:center!important;justify-content:center!important}.console-foot .cook-btn span{font-size:16px!important}@media(max-width:900px){.console-foot{flex-wrap:wrap!important}.console-foot .mission-link{width:100%!important}.console-foot .cook-btn{margin-left:auto!important}}';document.head.appendChild(st)};
  function addTimeline(){const rail=q('.right-rail');if(!rail||q('.live-timeline'))return;rail.insertAdjacentHTML('beforeend','<section class="live-timeline"><div class="feature-title"><span>LIVE AGENT ACTIVITY</span><b>STREAM</b></div><div class="timeline-list"><div class="timeline-empty">Waiting for a mission…</div></div></section>')}
  function metricsFor(name){const list=runs.filter(r=>r.agent_name===name),done=list.filter(r=>r.status==='completed'),failed=list.filter(r=>r.status==='failed');const times=done.map(r=>r.finished_at&&r.created_at?Math.max(0,new Date(r.finished_at)-new Date(r.created_at)):0).filter(Boolean);return {count:list.length,success:done.length,failed:failed.length,latency:times.length?Math.round(times.reduce((a,b)=>a+b,0)/times.length/1000):0}}
  function updateStations(){document.querySelectorAll('.station').forEach(s=>{const name=s.querySelector('h4')?.textContent.trim(),m=metricsFor(name);if(!name||s.querySelector('.agent-metrics'))return;s.insertAdjacentHTML('beforeend',`<div class="agent-metrics"><span>${m.count?m.success+'/'+m.count+' success':'no runs yet'}</span><span>${m.latency?m.latency+'s avg':'— latency'}</span></div>`)})}
  function updateTimeline(){fetch('/api/runs').then(r=>r.json()).then(data=>{runs=data||[];const list=q('.timeline-list');if(!list)return;const active=runs.filter(r=>r.status==='running').slice(0,6);list.innerHTML=active.length?active.map(r=>`<div class="timeline-item"><i class="${r.status}"></i><div><b>${esc(r.agent_name)}</b><span>${esc(r.task).slice(0,70)}</span></div><em>working</em></div>`).join(''):'<div class="timeline-empty"><i></i>All cooks are ready for work.</div>';updateStations()}).catch(()=>{})}
  function enhanceConnectors(){const grid=q('.integration-grid');if(!grid||grid.parentElement.querySelector('.scope-panel'))return;const scopes=getScopes();grid.insertAdjacentHTML('afterend',`<div class="scope-panel"><div class="feature-title"><span>MCP PERMISSION SCOPES</span><b>APPROVAL REQUIRED</b></div><p>Choose the access each connector may request. Write actions always pause for your approval.</p><div class="scope-grid">${['read','draft','write'].map(x=>`<label><input type="checkbox" data-scope="${x}" ${scopes[x]!==false?'checked':''}> ${x==='read'?'Read context':x==='draft'?'Create drafts':'Send / book (approval)'}</label>`).join('')}</div><button class="approval-demo" data-feature="approval-demo">Preview approval gate</button></div>`)}
  function attachOutputActions(){const out=q('.output-focus');if(!out||out.querySelector('.feature-actions'))return;const id=lastRun||q('[data-action="run-detail"]')?.dataset.run;out.insertAdjacentHTML('beforeend',`<div class="feature-actions"><button data-feature="export-md">Export Markdown</button><button data-feature="export-pdf">Print / PDF</button><button data-feature="replay">Replay mission</button></div>`);out.dataset.run=id||''}
  function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  function exportMarkdown(r){download(`agentos-mission-${r.id}.md`,`# ${r.agent_name} — mission ${r.id}\n\n**Status:** ${r.status}\n**Model:** ${r.model}\n**Created:** ${r.created_at}\n\n## Customer order\n${r.task}\n\n## Result\n${r.result||r.error||'Still cooking.'}\n`,'text/markdown')}
  function compare(){const ids=[...compared];if(ids.length<2)return window.toast?.('Select two missions to compare');Promise.all(ids.map(id=>fetch('/api/runs/'+id).then(r=>r.json()))).then(rs=>{const rows=rs.map(r=>`<div class="compare-card"><b>${esc(r.agent_name)} · ${esc(r.status)}</b><small>${esc(r.model)} · ${esc(r.created_at)}</small><p>${esc((r.result||r.error||'No result').slice(0,520))}</p></div>`).join('');window.openModal?.(`<div class="hub-kicker">MISSION ANALYSIS / COMPARISON</div><h2>Run comparison</h2><p class="hub-copy">Side-by-side outputs from your selected missions.</p><div class="compare-grid">${rows}</div><div class="modal-actions"><button class="primary" data-action="close">Done</button></div>`)})}
  document.addEventListener('click',e=>{
    const guide=e.target.closest('[data-action="guide"]');if(guide){e.preventDefault();e.stopImmediatePropagation();window.location.href='/guide';return}
    const run=e.target.closest('[data-action="run-detail"]');if(run){lastRun=run.dataset.run;setTimeout(attachOutputActions,120)}
    const cmp=e.target.closest('[data-compare-run]');if(cmp){e.preventDefault();e.stopPropagation();const id=cmp.dataset.compareRun;compared.has(id)?compared.delete(id):compared.add(id);cmp.classList.toggle('selected',compared.has(id));if(compared.size===2)compare()}
    const f=e.target.closest('[data-feature]');if(!f)return;const id=q('.output-focus')?.dataset.run||lastRun;if(f.dataset.feature==='export-pdf'){document.body.classList.add('printing');window.print();setTimeout(()=>document.body.classList.remove('printing'),500)}else if(f.dataset.feature==='export-md'&&id){fetch('/api/runs/'+id).then(r=>r.json()).then(exportMarkdown)}else if(f.dataset.feature==='replay'&&id){fetch('/api/runs/'+id).then(r=>r.json()).then(r=>{const t=q('#task');if(t)t.value=r.task;window.closeModal?.();window.toast?.('Mission loaded for replay — review agents, then dispatch')})}
    const scope=e.target.closest('[data-scope]');if(scope){const s=getScopes();s[scope.dataset.scope]=scope.checked;saveScopes(s)}
    if(e.target.closest('[data-feature="approval-demo"]'))window.openModal?.('<div class="hub-kicker">ACTION GATE / WRITE REQUEST</div><h2>Approval required</h2><p class="hub-copy">An agent wants to send a Slack update, email a draft, or book a Cal.com meeting. Nothing is sent until you approve the exact action.</p><div class="approval-request"><b>Requested action</b><span>Post a mission summary to the connected workspace</span><small>Scope: write · Connector: Slack MCP</small></div><div class="modal-actions"><button data-action="close">Deny</button><button class="primary" data-action="close">Approve once</button></div>');
  },true);
  const observer=new MutationObserver(()=>{addTimeline();enhanceConnectors();attachOutputActions();document.querySelectorAll('.run:not([data-feature-ready])').forEach(r=>{const id=r.dataset.run;if(!id)return;r.dataset.featureReady='1';r.insertAdjacentHTML('beforeend',`<span class="compare-chip" data-compare-run="${id}">Compare</span>`)})});
  const boot=()=>{inject();const tune=document.createElement('style');tune.textContent='.console-foot{display:grid!important;grid-template-columns:155px minmax(0,1fr) 150px!important;gap:10px!important}.console-foot .mode{min-width:0!important}.console-foot .mode select{width:140px!important;min-width:0!important;appearance:auto!important;color:#c6d6d8!important}.console-foot .cook-btn{width:150px!important;min-width:0!important}.top{gap:14px!important;min-width:0!important}.top .brand{flex:0 0 auto!important;white-space:nowrap!important}.top .location{display:flex!important;align-items:center!important;gap:7px!important;flex:0 1 320px!important;min-width:250px!important;white-space:nowrap!important;overflow:visible!important}.top .location span{white-space:nowrap!important}.top-search{flex:1 1 300px!important;min-width:190px!important;max-width:360px!important}.top-btn{white-space:nowrap!important;min-width:max-content!important}.top-btn.primary{min-width:138px!important}@media(max-width:1100px){.top .location{min-width:170px!important;flex-basis:240px!important}.top-search{max-width:280px!important}}@media(max-width:900px){.console-foot{display:flex!important;flex-wrap:wrap!important}.console-foot .mission-link{width:100%!important}.console-foot .cook-btn{margin-left:auto!important}}';document.head.appendChild(tune);const reset=document.createElement('style');reset.textContent='.floor h1{font-size:36px!important;line-height:1.04!important;letter-spacing:-.7px!important}.sub{font-size:11px!important;line-height:1.4!important}.line-title h2{font-size:20px!important}.order-console textarea{font-size:13px!important;line-height:1.55!important}.context-head h2{font-size:19px!important}.shelf-empty b{font-size:10px!important}.shelf-empty small{font-size:9px!important}.station-open h4{font-size:11px!important}.station .role{font-size:8px!important}.model-pill{font-size:8px!important}.station footer{font-size:8px!important}.cook-btn{height:42px!important;font-size:11px!important}.mode select{font-size:9px!important;height:34px!important}.top-btn{font-size:10px!important}.brand{font-size:15px!important}';document.head.appendChild(reset);addTimeline();updateTimeline();setInterval(updateTimeline,2500);observer.observe(document.body,{childList:true,subtree:true})};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,400));else setTimeout(boot,400);
})();
